export const FETCH_RECIPES = 'FETCH_RECIPES';
export const NEW_RECIPE = 'NEW_RECIPE';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';